import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import mainPic3 from '../public/main-3.svg'

function Home() {
  return (
    <div className="container">
      <Head>
        <title>Personal Frontend roadmap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.main__info}>
          <h1 className={styles.main__title}>
            Personal<span>Frontend Roadmap</span>
          </h1>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam at autem, blanditiis eaque error fuga labore, laborum magni, maxime odio officiis quod sed soluta? Amet asperiores ea quisquam quo tenetur!
          </p>
        </div>
        <Image src={mainPic3} alt='training' className={styles.main__image} />
    </main>

    </div>
  )
}

export default Home;
